### PR TITLE
gcc.specs: link: change '-PIE' to '-pie' and drop '-PIC'

### PR DESCRIPTION
**Pull request by floppym**
The ld manual does not mention -PIE or -PIC, and ld.gold fails when passed
either option.

The gcc manual mentions that -pie should be passed when linking objects
compiled with -fPIE.

Resolves: https://github.com/rhinstaller/efivar/issues/57

### CODE REVIEW

**Comment by vathpela** [comment]
We need --add-needed (though it has recently been renamed to "--copy-dt-needed-entries") because of https://sourceware.org/bugzilla/show_bug.cgi?id=19249 .  I don't offhand see a great way to avoid both sets of bugs at the same time: I can't drop Aarch64 , and ld.gold appears to simply be incomplete here. Is there a reason you can't build with ld.bfd instead?

**Comment by vathpela** [comment]
(I've pushed https://github.com/rhinstaller/efivar/pull/59/commits/6a5bf327b996b8a311ceccec081eb8fe680aa9ac to master, but not the --add-needed change.)

**Comment by floppym** [comment]
> Is there a reason you can't build with ld.bfd instead?

That's what I am currently doing in the Gentoo packaging. I just wanted to report the issue so it might get addressed eventually.

**Comment by vathpela** [comment]
This is still simply an ld.gold compatibility issue, not an efivar issue, so I'm going to go ahead and close this.

**Pull request closed without merging**
